version: "3.5"

services: 
    

   rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        container_name: rabbitmq
        networks:
            - default
            - my-proxy-net
        expose:
            - "5672"
            - "15672"
        ports:
            - "15672:15672"
            - "5672:5672"
   
   mongo:
        image: mongo:latest
        container_name: mongo
        hostname: mongo
        command: mongod --port 27018
        networks:
            - default
        volumes: 
        - data:/data/db
        ports:
        - "27018:27018"
        expose:
        - "27018"
        depends_on: 
        - rabbitmq

   app2:
        container_name: rabbit-consumer
        hostname: rabbit-consumer
        restart: always
        build: .
        command: nodemon /usr/src/app/rabbit_func.js
        networks:
            - default
        ports:
            - '3030:3000'
        volumes:
            - .:/usr/src/app
        depends_on: 
            - mongo
            - rabbitmq
       
networks:
    default: # this network (app2)
        driver: bridge
    my-proxy-net:
        external:
            name: custom_network

volumes: 
  data: