version: "3.8"
#Uncomment all
services: 

  fetch:
      container_name: fetch-node
      hostname: fetch-node
      restart: always
      build: .
      command: nodemon /usr/src/app/subscriber.js
      networks:
        - sub-faye
      ports:
        - '3030:3030'
      volumes:
        - .:/usr/src/app

  # prometheus:
    #  image: prom/prometheus:latest
    #  container_name: prometheus
    #  volumes:
    #   - ./prometheus.yml:/etc/prometheus/prometheus.yml
    #   - prometheus_data:/prometheus
    #  command:
    #   - '--config.file=/etc/prometheus/prometheus.yml'
    #   - '--storage.tsdb.path=/prometheus'
    #   - '--web.console.libraries=/etc/prometheus/console_libraries'
    #   - '--web.console.templates=/etc/prometheus/consoles'
    #   - '--web.enable-lifecycle'
    #  expose:
    #   - 9090
    #  ports:
    #   - 9090:9090

    # grafana:
    #  image: grafana/grafana
    #  container_name: grafana
    #  network_mode: host
    #  restart: always
    #  ports:
    #   - 9000:3000
    #  volumes:
    #   - grafana-data:/var/lib/grafana

networks:
   sub-faye:
     external:
       name: faye_sub

# volumes:
#   grafana-data:
#   prometheus_data: {}